name: Go Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout
    - name: Set up Go
      uses: actions/setup-go
      with:
        go-version: 1.20
      id: go
    - name: Test
      run: go test -v ./...
